import assert from 'node:assert/strict';
import {build} from 'esbuild';
const out=await build({stdin:{contents:"export {World,Faction} from './src/sim/world';export {SkirmishAI} from './src/ai/skirmish';",resolveDir:process.cwd()},bundle:true,write:false,platform:'node',format:'esm'});
const {World,Faction,SkirmishAI}=await import('data:text/javascript;base64,'+Buffer.from(out.outputFiles[0].text).toString('base64'));
function make(seed=81){const w=new World(64,64,seed,'plains',1,false);for(const id of [1,2,3])w.addPlayer(id,Faction.Human,['','blue','green','red'][id]);w.prepareCoop();for(const id of [1,2,3]){const p=w.map.starts[id-1];w.spawnStart(id,p.x-1,p.y-1);}w.updateVision(true);return w;}
for(const seed of [1,15,81,231]){const w=make(seed);assert.equal(w.buildings().length,3);const occupied=new Set();for(const b of w.buildings())for(let y=b.ty;y<b.ty+b.size;y++)for(let x=b.tx;x<b.tx+b.size;x++){assert(!occupied.has(`${x},${y}`),'camps cannot overlap');occupied.add(`${x},${y}`);}}
const w=make();assert(w.allied(1,2));assert(!w.allied(1,3));const ally=w.units().find(u=>u.owner===2);assert(w.canSeeEntity(1,ally));const soldier=w.spawnUnit(1,'footman',{...ally.pos});w.applyCommand({type:'attack',player:1,units:[soldier.id],target:ally.id});assert.notEqual(soldier.task.kind,'attack');const hp=ally.hp;w.dealDamage(ally,100,1);assert.equal(ally.hp,hp,'no friendly fire');
for(const e of [...w.entities.values()])if(e.owner===3)w.removeEntity(e.id);w.checkVictory();assert(w.allied(w.winner,1)&&w.allied(w.winner,2),'both humans win together');
const lost=make();for(const e of [...lost.entities.values()])if(e.owner!==3)lost.removeEntity(e.id);lost.checkVictory();assert.equal(lost.winner,3);
const a=make(),b=make(),aiA=new SkirmishAI(a,3,'normal'),aiB=new SkirmishAI(b,3,'normal');let orders=0;for(let tick=0;tick<1200;tick++){const ca=aiA.think(a.tick),cb=aiB.think(b.tick);orders+=ca.length;assert.deepEqual(ca,cb);a.step(ca);b.step(cb);assert.equal(a.checksum(),b.checksum(),`synchronized tick ${tick}`);}assert(orders>10,'AI develops its kingdom');console.log('PASS: co-op camps, shared sight, friendly-fire protection, team victory/defeat and 1200 synchronized AI ticks.');
