import {chromium} from 'playwright';import {readFileSync} from 'node:fs';import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
try{
 const p=await browser.newPage({viewport:{width:1280,height:900}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.setContent(readFileSync('dist/index.html','utf8'));await p.waitForFunction(()=>window.game);
 await p.evaluate(()=>{const g=window.game;g.runFront({kind:'pane',pane:'multiplayer'});g.openRoom=async setup=>{window.capturedSetup=setup;};g.runFront({kind:'host'});});
 const dialog=p.getByRole('dialog',{name:'Create your game'});await dialog.waitFor();await dialog.getByLabel('Map',{exact:true}).selectOption('plains-7925');await dialog.getByLabel('Match length').selectOption('4');await dialog.getByLabel('Starting army').selectOption('settled');await dialog.getByLabel('Wildlife',{exact:true}).uncheck();await dialog.getByLabel('Forest walls').check();await p.screenshot({path:'test/artifacts/create-game.png'});
 await p.getByRole('button',{name:'Create room',exact:true}).click();assert(await dialog.isHidden());const setup=await p.evaluate(()=>window.capturedSetup);assert.equal(setup.mode,'coop');assert.equal(setup.aiDifficulty,'normal');assert.equal(setup.mapId,'plains-7925');assert.equal(setup.pace,4);assert(!setup.crowning&&!setup.nomad&&!setup.wildlife&&setup.stockade);
 await p.evaluate(()=>window.game.runFront({kind:'host'}));await p.setViewportSize({width:390,height:740});const bounds=await dialog.boundingBox();assert(bounds.x>=0&&bounds.x+bounds.width<=390);await p.screenshot({path:'test/artifacts/create-game-mobile.png'});await p.keyboard.press('Escape');assert(await dialog.isHidden());
 await p.setViewportSize({width:1280,height:900});await p.evaluate(()=>{const g=window.game;Object.assign(g.settingsForTest,{voices:false,crowning:false,stockade:false,wildlife:false});g.start('none');g.tick=()=>{};const w=g.world;w.fogEnabled=false;for(const e of [...w.entities.values()])w.removeEntity(e.id);for(let y=0;y<w.map.height;y++)for(let x=0;x<w.map.width;x++)w.map.set(x,y,0);w.placeBuilding(1,'lumbermill',14,20,true);w.placeBuilding(1,'golddepot',22,20,true);g.cam.zoom=65;g.cam.centerOn(21*64,23*64);});await p.waitForTimeout(1000);await p.screenshot({path:'test/artifacts/mill-and-depot.png'});assert.deepEqual(errors,[]);console.log('PASS: custom setup form, submitted rules, mobile bounds, Escape, building render without errors.');
}finally{await browser.close();}

