import {chromium} from 'playwright';import {readFileSync} from 'node:fs';import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
try{const p=await browser.newPage({viewport:{width:1280,height:900}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.setContent(readFileSync('dist/index.html','utf8'));await p.waitForFunction(()=>window.game);
let points=await p.evaluate(()=>{const g=window.game;Object.assign(g.settingsForTest,{clickToMove:true,crowning:false,stockade:false,wildlife:false,edgeScroll:false,voices:false});g.start('none');g.paused=true;const w=g.world;w.fogEnabled=false;for(const e of [...w.entities.values()])w.removeEntity(e.id);for(let y=0;y<w.map.height;y++)for(let x=0;x<w.map.width;x++)w.map.set(x,y,0);const u=w.spawnUnit(1,'worker',{x:20.5*64,y:20.5*64});g.selected.clear();g.cam.zoom=40;g.cam.centerOn(u.pos.x+100,u.pos.y);window.controlUnit=u.id;const box=g.canvas.getBoundingClientRect(),body=g.cam.toScreen(u.pos.x,u.pos.y-.8*64),ground=g.cam.toScreen(u.pos.x+5*64,u.pos.y);return {body:{x:box.left+body.x,y:box.top+body.y},ground:{x:box.left+ground.x,y:box.top+ground.y}};});
await p.waitForTimeout(300);
points=await p.evaluate(()=>{const g=window.game,u=g.world.entities.get(window.controlUnit),box=g.canvas.getBoundingClientRect(),body=g.cam.toScreen(u.pos.x,u.pos.y-.8*64),ground=g.cam.toScreen(u.pos.x+5*64,u.pos.y);return {body:{x:box.left+body.x,y:box.top+body.y},ground:{x:box.left+ground.x,y:box.top+ground.y}};});
await p.mouse.move(points.body.x,points.body.y);await p.mouse.down();await p.mouse.move(points.body.x+4,points.body.y+3);await p.mouse.up();assert(await p.evaluate(()=>window.game.selected.has(window.controlUnit)),'body click with slight wobble selects unit');
await p.mouse.click(points.ground.x,points.ground.y);assert(await p.evaluate(()=>window.game.selected.has(window.controlUnit)),'ground click keeps selection');const moved=await p.evaluate(()=>{const g=window.game,u=g.world.entities.get(window.controlUnit),x=u.pos.x;for(let i=0;i<35;i++)g.tick();return u.pos.x>x;});assert(moved,'left click actually moves unit');
await p.evaluate(()=>{const g=window.game;g.keys.add('arrowright');g.drag={x0:0,y0:0,x1:1,y1:1};window.dispatchEvent(new Event('blur'));});assert(await p.evaluate(()=>window.game.keys.size===0&&window.game.drag===null));
await p.evaluate(()=>{const g=window.game;g.selected.clear();g.cam.centerOn(50*64,50*64);});await p.keyboard.press('Home');assert(await p.evaluate(()=>window.game.selected.has(window.controlUnit)));assert.deepEqual(errors,[]);console.log('PASS: visible-body selection, click wobble, left-click movement, preserved selection, blur cleanup and Home shortcut.');}finally{await browser.close();}
