import {chromium} from 'playwright';import {readFileSync} from 'node:fs';import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
try{const p=await browser.newPage({viewport:{width:1440,height:950}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.setContent(readFileSync('dist/index.html','utf8'));await p.waitForFunction(()=>window.game);
await p.evaluate(()=>{const g=window.game;Object.assign(g.settingsForTest,{voices:false,crowning:false,stockade:false,wildlife:false,edgeScroll:false});g.start('none');g.tick=()=>{};g.issue=c=>g.world.applyCommand(c);const w=g.world;w.fogEnabled=false;w.tick=1200;for(const e of [...w.entities.values()])w.removeEntity(e.id);for(let y=0;y<w.map.height;y++)for(let x=0;x<w.map.width;x++)w.map.set(x,y,0);for(const [i,level] of [1,5,10].entries()){const b=w.placeBuilding(1,'lumbermill',14+i*11,19,true);b.level=level;}const tower=w.placeBuilding(1,'tower',46,19,true);window.previewTower=tower.id;w.placeBuilding(1,'farm',14,27,true);w.spawnUnit(1,'footman',{x:19*64,y:22*64});w.players.get(1).gold=10000;w.players.get(1).lumber=10000;g.selected=new Set([w.buildings()[0].id]);g.tab='build';g.cam.zoom=31;g.cam.centerOn(31*64,18.5*64);});await p.waitForTimeout(1800);
assert.equal(await p.locator('.rv-tile.upgrade').count(),1);assert(await p.getByText('Upgrade to Level 2',{exact:true}).count());await p.screenshot({path:'test/artifacts/lumbermill-tiers.png'});
await p.getByText('Upgrade to Level 2',{exact:true}).click();await p.waitForTimeout(100);assert(await p.getByText('Cancel Upgrade',{exact:true}).count());await p.getByText('Cancel Upgrade',{exact:true}).click();
const result=await p.evaluate(()=>{const g=window.game,w=g.world,b=w.entities.get(window.previewTower);let occupied=0;for(const id of w.map.occupant)if(id===b.id)occupied++;return {size:b.size,occupied};});assert.deepEqual(result,{size:3,occupied:9});assert.deepEqual(errors,[]);console.log('PASS: next-level card, click/cancel upgrade, 3x3 outpost collision footprint and Lumber Mill tier render');
}finally{await browser.close();}

