import {chromium} from 'playwright';import {readFileSync} from 'node:fs';import assert from 'node:assert/strict';
const browser=await chromium.launch({executablePath:'C:/Program Files/Google/Chrome/Application/chrome.exe'});
try {const page=await browser.newPage({viewport:{width:1440,height:950}}),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.setContent(readFileSync('dist/index.html','utf8'));await page.waitForFunction(()=>window.game);
await page.evaluate(()=>{const g=window.game;Object.assign(g.settingsForTest,{voices:false,crowning:false,stockade:false,wildlife:false,edgeScroll:false});g.start('none');g.tick=()=>{};const w=g.world;w.fogEnabled=false;w.tick=1200;for(const e of [...w.entities.values()])w.removeEntity(e.id);for(let y=0;y<w.map.height;y++)for(let x=0;x<w.map.width;x++)w.map.set(x,y,0);
const tiles=new Set(),put=(x,y)=>tiles.add(x+','+y);for(let x=15;x<=27;x++){put(x,14);if(x!==21&&x!==22)put(x,24);}for(let y=15;y<24;y++){put(15,y);put(27,y);}for(let x=16;x<27;x++)put(x,19);for(let y=15;y<24;y++)put(23,y);for(const key of tiles){const [x,y]=key.split(',').map(Number);w.placeBuilding(1,'wall',x,y,true);}w.placeBuilding(1,'tower',17,16,true);w.placeBuilding(1,'shelter',17,21,true);w.placeBuilding(1,'torch',20,21,true);const k=w.spawnUnit(1,'king',{x:21.5*64,y:25.5*64});g.selected=new Set([k.id]);g.tab='build';g.cam.zoom=40;g.cam.centerOn(21.5*64,20*64);});await page.waitForTimeout(1600);
const masks=await page.evaluate(()=>{const g=window.game;return [g.renderer.wallConnections(15,14,1),g.renderer.wallConnections(23,19,1),g.renderer.wallConnections(20,24,1)];});assert.deepEqual(masks,[6,15,8]);
await page.screenshot({path:'test/artifacts/joined-walls.png'});
await page.evaluate(()=>{const w=window.game.world,b=w.buildings().find(b=>b.def==='wall'&&b.tx===24&&b.ty===19);w.removeEntity(b.id);});assert.equal(await page.evaluate(()=>window.game.renderer.wallConnections(23,19,1)),13);
await page.evaluate(()=>{const g=window.game;g.buildMode='wall';g.wallStart={x:20,y:27};const p=g.cam.toScreen(25.5*64,27.5*64);g.mouse={x:p.x,y:p.y,inside:true};});await page.waitForTimeout(100);await page.screenshot({path:'test/artifacts/wall-drag-preview.png'});assert.deepEqual(errors,[]);console.log('PASS: corners, cross, end cap, deletion reconnect and drag preview; no browser errors');
}finally{await browser.close();}

