/**
 * The map catalogue.
 *
 * Generated by tools/make_maps.mjs, which builds candidates across every layout
 * and throws away the ones that are not worth playing: starts with no land route
 * between them, a start short of timber, gold or shoreline, or a board with too
 * little open ground to build on. Only survivors are listed here, so every entry
 * is known-playable rather than merely known-different.
 *
 * Regenerate with: node tools/make_maps.mjs
 */

import type { MapKind } from "../sim/map";

export interface MapDef {
  id: string;
  name: string;
  kind: MapKind;
  seed: number;
  /** Board edge in tiles. */
  size: number;
  /** Fraction of the board that is open ground, as a rough openness rating. */
  open: number;
}

export const MAPS: MapDef[] = [
  { id: "lakeland-7927", name: "Still Water", kind: "lakeland", seed: 7927, size: 160, open: 0.679 },
  { id: "gorge-7924", name: "Black Ravine", kind: "gorge", seed: 7924, size: 160, open: 0.73 },
  { id: "highlands-7928", name: "Thorn Fell", kind: "highlands", seed: 7928, size: 160, open: 0.643 },
  { id: "plains-7925", name: "Open Steppe", kind: "plains", seed: 7925, size: 160, open: 0.592 },
  { id: "islands-7926", name: "Foam Chain", kind: "islands", seed: 7926, size: 160, open: 0.647 },
  { id: "lakeland-15846", name: "Mirror Lake", kind: "lakeland", seed: 15846, size: 160, open: 0.688 },
  { id: "gorge-15843", name: "Sunder Cut", kind: "gorge", seed: 15843, size: 160, open: 0.739 },
  { id: "plains-15844", name: "Fallow Expanse", kind: "plains", seed: 15844, size: 160, open: 0.583 },
  { id: "islands-15845", name: "Storm Isles", kind: "islands", seed: 15845, size: 160, open: 0.627 },
  { id: "lakeland-23765", name: "Rush Shallows", kind: "lakeland", seed: 23765, size: 160, open: 0.699 },
  { id: "gorge-23762", name: "Grim Defile", kind: "gorge", seed: 23762, size: 160, open: 0.743 },
  { id: "highlands-23766", name: "Frost Tor", kind: "highlands", seed: 23766, size: 160, open: 0.641 },
  { id: "plains-23763", name: "Broad Downs", kind: "plains", seed: 23763, size: 160, open: 0.6 },
  { id: "lakeland-31684", name: "Willow Lake", kind: "lakeland", seed: 31684, size: 160, open: 0.694 },
  { id: "gorge-31681", name: "Stone Cut", kind: "gorge", seed: 31681, size: 160, open: 0.748 },
  { id: "highlands-31685", name: "Eagle Crest", kind: "highlands", seed: 31685, size: 160, open: 0.657 },
  { id: "plains-31682", name: "Far Fields", kind: "plains", seed: 31682, size: 160, open: 0.572 },
  { id: "islands-31683", name: "Gull Shoals", kind: "islands", seed: 31683, size: 160, open: 0.627 },
  { id: "lakeland-39603", name: "Silver Pool", kind: "lakeland", seed: 39603, size: 160, open: 0.668 },
  { id: "gorge-39600", name: "Cold Pass", kind: "gorge", seed: 39600, size: 160, open: 0.73 },
  { id: "highlands-39604", name: "Bleak Heights", kind: "highlands", seed: 39604, size: 160, open: 0.641 },
  { id: "plains-39601", name: "Bright Run", kind: "plains", seed: 39601, size: 160, open: 0.591 },
  { id: "islands-39602", name: "Tide Straits", kind: "islands", seed: 39602, size: 160, open: 0.608 },
  { id: "lakeland-47522", name: "Marsh Reach", kind: "lakeland", seed: 47522, size: 160, open: 0.669 },
  { id: "gorge-47519", name: "Iron Gorge", kind: "gorge", seed: 47519, size: 160, open: 0.732 },
  { id: "highlands-47523", name: "Granite Scarp", kind: "highlands", seed: 47523, size: 160, open: 0.637 },
  { id: "plains-47520", name: "Ember Plain", kind: "plains", seed: 47520, size: 160, open: 0.597 },
  { id: "islands-47521", name: "Coral Sound", kind: "islands", seed: 47521, size: 160, open: 0.634 },
  { id: "lakeland-55441", name: "Pike Bend", kind: "lakeland", seed: 55441, size: 160, open: 0.668 },
  { id: "gorge-55438", name: "Cleft Crossing", kind: "gorge", seed: 55438, size: 160, open: 0.738 },
  { id: "highlands-55442", name: "Wind Bluff", kind: "highlands", seed: 55442, size: 160, open: 0.638 },
  { id: "plains-55439", name: "Broad Plain", kind: "plains", seed: 55439, size: 160, open: 0.578 },
  { id: "lakeland-63360", name: "Otter Water", kind: "lakeland", seed: 63360, size: 160, open: 0.696 },
  { id: "gorge-63357", name: "Bitter Ravine", kind: "gorge", seed: 63357, size: 160, open: 0.75 },
  { id: "highlands-63361", name: "Storm Fell", kind: "highlands", seed: 63361, size: 160, open: 0.649 },
  { id: "islands-63359", name: "Pearl Sound", kind: "islands", seed: 63359, size: 160, open: 0.632 },
  { id: "lakeland-71279", name: "Still Bend", kind: "lakeland", seed: 71279, size: 160, open: 0.677 },
  { id: "gorge-71276", name: "Black Crossing", kind: "gorge", seed: 71276, size: 160, open: 0.723 },
  { id: "highlands-71280", name: "Thorn Bluff", kind: "highlands", seed: 71280, size: 160, open: 0.633 },
  { id: "plains-71277", name: "Open Expanse", kind: "plains", seed: 71277, size: 160, open: 0.619 },
  { id: "islands-71278", name: "Foam Isles", kind: "islands", seed: 71278, size: 160, open: 0.611 },
  { id: "lakeland-79198", name: "Mirror Shallows", kind: "lakeland", seed: 79198, size: 160, open: 0.683 },
  { id: "gorge-79195", name: "Sunder Defile", kind: "gorge", seed: 79195, size: 160, open: 0.722 },
  { id: "highlands-79199", name: "Grey Tor", kind: "highlands", seed: 79199, size: 160, open: 0.651 },
  { id: "plains-79196", name: "Wheat Downs", kind: "plains", seed: 79196, size: 160, open: 0.593 },
  { id: "islands-79197", name: "Mist Bay", kind: "islands", seed: 79197, size: 160, open: 0.629 },
  { id: "lakeland-87117", name: "Heron Basin", kind: "lakeland", seed: 87117, size: 160, open: 0.671 },
  { id: "gorge-87114", name: "Deep Gate", kind: "gorge", seed: 87114, size: 160, open: 0.759 },
  { id: "highlands-87118", name: "High Ridge", kind: "highlands", seed: 87118, size: 160, open: 0.646 },
  { id: "islands-87116", name: "Drift Shoals", kind: "islands", seed: 87116, size: 160, open: 0.618 },
  { id: "lakeland-95036", name: "Tern Pool", kind: "lakeland", seed: 95036, size: 160, open: 0.674 },
  { id: "gorge-95033", name: "Narrow Pass", kind: "gorge", seed: 95033, size: 160, open: 0.734 },
  { id: "highlands-95037", name: "Raven Heights", kind: "highlands", seed: 95037, size: 160, open: 0.647 },
  { id: "plains-95034", name: "Golden Run", kind: "plains", seed: 95034, size: 160, open: 0.598 },
  { id: "islands-95035", name: "Anchor Straits", kind: "islands", seed: 95035, size: 160, open: 0.64 },
  { id: "lakeland-102955", name: "Alder Reach", kind: "lakeland", seed: 102955, size: 160, open: 0.693 },
  { id: "gorge-102952", name: "Hollow Gorge", kind: "gorge", seed: 102952, size: 160, open: 0.741 },
  { id: "highlands-102956", name: "Shale Scarp", kind: "highlands", seed: 102956, size: 160, open: 0.653 },
  { id: "plains-102953", name: "Long Plain", kind: "plains", seed: 102953, size: 160, open: 0.575 },
  { id: "islands-102954", name: "Foam Straits", kind: "islands", seed: 102954, size: 160, open: 0.632 },
  { id: "lakeland-110874", name: "Mirror Reach", kind: "lakeland", seed: 110874, size: 160, open: 0.678 },
  { id: "gorge-110871", name: "Sunder Gorge", kind: "gorge", seed: 110871, size: 160, open: 0.757 },
  { id: "highlands-110875", name: "Grey Scarp", kind: "highlands", seed: 110875, size: 160, open: 0.639 },
  { id: "plains-110872", name: "Wheat Plain", kind: "plains", seed: 110872, size: 160, open: 0.609 },
  { id: "lakeland-118793", name: "Pike Water", kind: "lakeland", seed: 118793, size: 160, open: 0.67 },
  { id: "gorge-118790", name: "Cleft Ravine", kind: "gorge", seed: 118790, size: 160, open: 0.736 },
  { id: "highlands-118794", name: "Wind Fell", kind: "highlands", seed: 118794, size: 160, open: 0.637 },
  { id: "plains-118791", name: "Fallow Steppe", kind: "plains", seed: 118791, size: 160, open: 0.586 },
  { id: "islands-118792", name: "Storm Chain", kind: "islands", seed: 118792, size: 160, open: 0.626 },
  { id: "lakeland-126712", name: "Rush Lake", kind: "lakeland", seed: 126712, size: 160, open: 0.686 },
  { id: "gorge-126709", name: "Grim Cut", kind: "gorge", seed: 126709, size: 160, open: 0.743 },
  { id: "highlands-126713", name: "Frost Crest", kind: "highlands", seed: 126713, size: 160, open: 0.625 },
  { id: "plains-126710", name: "Broad Fields", kind: "plains", seed: 126710, size: 160, open: 0.578 },
  { id: "lakeland-134631", name: "Willow Shallows", kind: "lakeland", seed: 134631, size: 160, open: 0.674 },
  { id: "gorge-134628", name: "Stone Defile", kind: "gorge", seed: 134628, size: 160, open: 0.739 },
  { id: "highlands-134632", name: "Eagle Tor", kind: "highlands", seed: 134632, size: 160, open: 0.632 },
  { id: "plains-134629", name: "Far Downs", kind: "plains", seed: 134629, size: 160, open: 0.587 },
  { id: "islands-134630", name: "Gull Bay", kind: "islands", seed: 134630, size: 160, open: 0.631 },
  { id: "lakeland-142550", name: "Silver Basin", kind: "lakeland", seed: 142550, size: 160, open: 0.662 },
  { id: "gorge-142547", name: "Cold Gate", kind: "gorge", seed: 142547, size: 160, open: 0.732 },
  { id: "highlands-142551", name: "Bleak Ridge", kind: "highlands", seed: 142551, size: 160, open: 0.621 },
  { id: "plains-142548", name: "Bright Meadow", kind: "plains", seed: 142548, size: 160, open: 0.598 },
  { id: "islands-142549", name: "Tide Skerries", kind: "islands", seed: 142549, size: 160, open: 0.649 },
  { id: "lakeland-150469", name: "Marsh Mere", kind: "lakeland", seed: 150469, size: 160, open: 0.668 },
  { id: "gorge-150466", name: "Iron Chasm", kind: "gorge", seed: 150466, size: 160, open: 0.747 },
  { id: "highlands-150470", name: "Granite Moor", kind: "highlands", seed: 150470, size: 160, open: 0.642 },
  { id: "plains-150467", name: "Ember Flats", kind: "plains", seed: 150467, size: 160, open: 0.561 },
  { id: "islands-150468", name: "Coral Reef", kind: "islands", seed: 150468, size: 160, open: 0.606 },
  { id: "lakeland-158388", name: "Rush Mere", kind: "lakeland", seed: 158388, size: 160, open: 0.69 },
  { id: "gorge-158385", name: "Grim Chasm", kind: "gorge", seed: 158385, size: 160, open: 0.737 },
  { id: "highlands-158389", name: "Frost Moor", kind: "highlands", seed: 158389, size: 160, open: 0.638 },
  { id: "plains-158386", name: "Broad Flats", kind: "plains", seed: 158386, size: 160, open: 0.593 },
  { id: "islands-158387", name: "Drift Reef", kind: "islands", seed: 158387, size: 160, open: 0.618 },
  { id: "lakeland-166307", name: "Tern Water", kind: "lakeland", seed: 166307, size: 160, open: 0.688 },
  { id: "gorge-166304", name: "Narrow Ravine", kind: "gorge", seed: 166304, size: 160, open: 0.748 },
  { id: "highlands-166308", name: "Raven Fell", kind: "highlands", seed: 166308, size: 160, open: 0.638 },
  { id: "plains-166305", name: "Golden Steppe", kind: "plains", seed: 166305, size: 160, open: 0.588 },
  { id: "islands-166306", name: "Anchor Chain", kind: "islands", seed: 166306, size: 160, open: 0.621 },
  { id: "lakeland-174226", name: "Alder Lake", kind: "lakeland", seed: 174226, size: 160, open: 0.686 },
  { id: "gorge-174223", name: "Hollow Cut", kind: "gorge", seed: 174223, size: 160, open: 0.75 },
];

export const MAP_BY_ID = new Map(MAPS.map((m) => [m.id, m]));

/** Human-readable blurb for a layout, for the map picker. */
export const KIND_BLURB: Record<MapKind, string> = {
  lakeland: "A great lake with rivers running east and west. Open and even.",
  gorge: "A broad river cuts the board, crossed in only a few places.",
  highlands: "Rock ridges everywhere. Armies wind between walls.",
  plains: "Open ground and heavy timber. Fast, and nowhere to hide.",
  islands: "Water is the rule and land the exception. Shorelines everywhere.",
  seas: "Open water, with land in scattered holdings. Naval.",
};
